title: "{{PROJECT_NAME}}"
subtitle: "{{PROJECT_TYPE}}"
author: "{{AUTHOR_NAME}}"

mainfont: "Noto Serif"
documentclass: book
classoption: [oneside]

lang: fr-FR
babel-lang: french

indent: true
parindent: 1.2em
parskip: 0.5em

pagestyle: headings
secnumdepth: 0
toc: true
toc-title: "Sommaire"
toc-depth: 1

header-includes: |
  \usepackage{setspace}
  \setlength{\emergencystretch}{3em}
  \setlength{\parskip}{0.5em}
  \setlength{\parindent}{1.2em}
  \widowpenalty=10000
  \clubpenalty=10000

colorlinks: false
links-as-notes: false

pdf-engine: xelatex
